### ISSUE TITLE
Allow gpx import

### ISSUE THREAD

**Issue by borisrorsvort** [WelcometoMyGarden/welcometomygarden#102]
If you could allow to import a gpx with your itinerary, it would be so much easier to find hosts along the way 👍 

- manual import
- import from 3rd party tracker apps like komoot, ...

**Comment by th0rgall** [comment]
Hey @borisrorsvort & @beaumkr, we've released a first version of this feature!
<img width="743" alt="CleanShot 2023-01-12 at 20 30 32@2x" src="https://user-images.githubusercontent.com/11543641/212101066-e247f436-4217-4ef5-aaa1-fdb746b420f5.png">

@wardbeyens figured out how to do this in-browser with MapLibre GL JS. By using [@tmcw/togeojson](https://www.npmjs.com/package/@tmcw/togeojson), there is even support already for tracks in `.geojson`, `.kml`, `.tcx` file formats (this package is more maintained than MapBox's togeojson, and fits our ES modules project better).

This first version does not persist uploaded tracks as account data. That's likely something we will add later :) 

The entry point of this code is [here](https://github.com/WelcometoMyGarden/welcometomygarden/blob/eaafd66c20734c1d5de52ac30a61f0502aa606ce/src/lib/components/LayersAndTools/TrailsTool.svelte#L37-L63), but in production it is reserved as a special feature for Superfans (more info: https://welcometomygarden.org/about-superfan).

I just opened a [GitHub Discussions](https://github.com/WelcometoMyGarden/welcometomygarden/discussions) tab for WTMG, I will add GPX import from 3rd party tracker apps as an idea.
