### ISSUE TITLE
Gardens not showing up on mobile

### ISSUE THREAD

**Issue by ludov04** [WelcometoMyGarden/welcometomygarden#105]
When navigating to the mobile app, the gardens are not showing up.
It then appears if I go back to the "Home" tab and then again to the "Map.

Steps to reproduce:
1. Go to https://welcometomygarden.org/ on mobile
2. Go to map
  - The map is showing but not the gardens
3. Go back to home, then again to map
  - The gardens are now showing 

![IMG_1451 2](https://user-images.githubusercontent.com/1741726/116531289-eb5adb80-a8d6-11eb-94f1-d40227aaff85.PNG)

**Comment by MichielLeyman** [comment]
Hey @ludov04, thanks for reporting. Is this something you've only ran into on Safari? I can't seem to reproduce on my device.

**Comment by ludov04** [comment]
@MichielLeyman Yes, on Safari on iPhone
