### ISSUE TITLE
[v2] Migrate to svelte-kit

### ISSUE THREAD

**Issue by micleyman** [WelcometoMyGarden/welcometomygarden#111]
[svelte-kit](https://kit.svelte.dev/) is Sapper's replacement and will give us much more control over our app's optimization & build process. We can also explore dropping Routify for Kit's included router.

At the time of creating this issue, Kit is still in beta. See https://github.com/sveltejs/kit/milestone/2 for progress.

**Comment by th0rgall** [comment]
We haven't made progress on the non-Firebase V2, but we have migrated the current Firebase version fully to SvelteKit 1.0.
