### ISSUE TITLE
[v2] Folder & local build step restructure

### ISSUE THREAD

**Issue by micleyman** [WelcometoMyGarden/welcometomygarden#120]
- [ ] Redo the folders and cut Firebase out of the picture
- [ ] Add NestJS starter
- [ ] Dockerize entire thing, but ensure front-end stays runnable locally
- [ ] Add runtime instructions right away & pay special attention to env variables

**Comment by th0rgall** [comment]
I'm closing this since a v2 rewrite is currently not on the roadmap.
