### ISSUE TITLE
[v2] Authentication & Authorization

### ISSUE THREAD

**Issue by micleyman** [WelcometoMyGarden/welcometomygarden#121]
Use https://docs.nestjs.com/security/authentication as a guide line and pay special attention to cookie policy & security. Scope refresh tokens to just the endpoint used to refresh them.

Add authorization middleware so we can authorize users for a given endpoint later.
Test, test, test

OR [Keycloak](https://www.keycloak.org/) with Passport strategy

**Comment by th0rgall** [comment]
I'm closing this since a v2 rewrite is currently not on the roadmap.
