### ISSUE TITLE
[v2] Chat

### ISSUE THREAD

**Issue by micleyman** [WelcometoMyGarden/welcometomygarden#124]
Research is to be done for the best way to approach this. It will likely be a mix of Socket.io & Redis.

Tight coupling with Firebase in the front-end needs to be redone, & we should very much keep federation possibilities in mind (#108)

- [ ] Front-end should remain working as-is
- [ ] Back-end should incorporate or at least allow for the requested changes to chat:
  - [ ] #41 
  - [ ] #63
  - [ ] #97

**Comment by th0rgall** [comment]
I'm closing this since a v2 rewrite is currently not on the roadmap.
