### ISSUE TITLE
Bug with email notifications for new chats

### ISSUE THREAD

**Issue by Manonbd** [WelcometoMyGarden/welcometomygarden#135]
Through support (email and facebook), some users communicate that they no longer receive email notifications for new chats.

**Comment by MichielLeyman** [comment]
Seems like reports for this have stopped, and I can't reproduce anything. Logs show no problems.
Maybe it was due to that recent Sendgrid outage?


Feel free to open a new issue if you get more people reporting this problem, and thanks for creating an issue :)
