### ISSUE TITLE
Why not hosting git repository on gitlab.com instead of github.com?

### ISSUE THREAD

**Issue by Agnox** [WelcometoMyGarden/welcometomygarden#28]

**Comment by MichielLeyman** [comment]
The short answer: because it's what we're used to :)

I'd be happy to try out GitLab. Why do you prefer it?

**Comment by Agnox** [comment]
Gitlab is an open source product so I think it more reflects the thoughts of 'Welcome To My Garden' of being community driven. Just like you are using OSM instead of Google Maps or Bing Maps.

**Comment by pietercolpaert** [comment]
Github allows to reach out to a larger community at this moment. From the moment gitlab allows decentralized user profiles and makes that user-friendly I will be advocating it to become our default at Open Knowledge Belgium. I hope you’re not going around every and each of our repositories to open that issue though ;-)

**Comment by MichielLeyman** [comment]
Thank you for the feedback, and thanks for weighing in!
