### ISSUE TITLE
Select the radio button by clicking on the text

### ISSUE THREAD

**Issue by wardbeyens** [WelcometoMyGarden/welcometomygarden#290]
You can no longer select the radio button by clicking on the text

![image](https://user-images.githubusercontent.com/45149049/212699428-cbaad53e-6291-47cb-872e-a7db4d36f210.png)

**Comment by carlos-ds** [comment]
Hi, I've made #303 for this.

**Comment by th0rgall** [comment]
This was collateral damage from me clumsily refactoring common code between radio buttons and checkboxes with icons into `<LabelWithIcon>` (radio buttons could not have icons before the refactor). Your PR fixed it @carlos-ds, thanks!
