### ISSUE TITLE
Add a fullscreen control to the map

### ISSUE THREAD

**Issue by th0rgall** [WelcometoMyGarden/welcometomygarden#301]
### Discussed in https://github.com/WelcometoMyGarden/welcometomygarden/discussions/285

<div type='discussions-op-text'>

<sup>Originally posted by **patrickhoebeke** July 27, 2022</sup>
The map currently miss a fullscreen control.
Indeed, currently, the bottom part of the site takes a low of useless space... Especially when the app is used on a smart phone.
It seems to be relatively straightforward to add : https://docs.mapbox.com/mapbox-gl-js/example/fullscreen/
But I have very limited competence to do it myself :-)

It would be very great if someone could do it !

Thanks a lot,

Patrick</div>

Implementation plan: https://github.com/WelcometoMyGarden/welcometomygarden/discussions/285#discussioncomment-4788900

**Comment by mclaeysb** [comment]
Yup, great improvement, thanks for the reply and follow up!

**Comment by th0rgall** [comment]
This has been released by now!
