### ISSUE TITLE
Bug scroll issue in full screen mode

### ISSUE THREAD

**Issue by wardbeyens** [WelcometoMyGarden/welcometomygarden#320]
I Can't scroll after I get redirected while still in fullscreen mode.

https://user-images.githubusercontent.com/45149049/234035231-225290c3-9b7c-4b57-aaa6-846a7ccd1e7f.webm

**Comment by th0rgall** [comment]
Ah, thanks for reporting! 

Scrolling seems to work when I change `'body'` to `'html'` here https://github.com/WelcometoMyGarden/welcometomygarden/blob/4380a2598670384860b8c3e9684fa59c61029629/src/lib/components/Map/Map.svelte#L83-L88

but being able to navigate away from the map view while still in full-screen mode might lead to more unexpected situations. Maybe we will depend on the nav bars in other parts of the app. It's probably better to automatically exit fullscreen when exiting the map. I'll try to find if we can do that cleanly.

**Comment by th0rgall** [comment]
I think I found a way, see the commit linked above. Let me know if it is still broken.
