### ISSUE TITLE
Links in footer don't seem to work

### ISSUE THREAD

**Issue by jbelien** [WelcometoMyGarden/welcometomygarden#33]
The following links don't seem to do anything:

- Cookie policy 
- Privacy policy
- Terms of use

And when I try to open the direct link I have a "blank" page : https://welcometomygarden.org/terms/privacy-policy

**Comment by MichielLeyman** [comment]
I think this may have been a cache issue since the hash for those pages changed.

This works fine for me though.
Could you try again and confirm it's working for you as well?

**Comment by jbelien** [comment]
Working fine now ! 👌
