### ISSUE TITLE
Z-index of footer to be lowered

### ISSUE THREAD

**Issue by wietsevr** [WelcometoMyGarden/welcometomygarden#38]
<img width="1263" alt="Screen Shot 2020-06-25 at 23 17 14" src="https://user-images.githubusercontent.com/11728606/85796338-0ea67e80-b73a-11ea-939c-9c438e09cb5a.png">
Icons of the footer appear on top of the images. Lowering the z-index of the footer could be a quick fix.

**Comment by MichielLeyman** [comment]
The footer isn't positioned so a z-index won't affect it. Strange how these icons show on top, I'll check this out

**Comment by nicklace** [comment]
The .magnified-photo-wrapper overlay div should be same level than footer (suggestion: just before </body>) to fix this.

**Comment by MichielLeyman** [comment]
Fixed in #118
