### ISSUE TITLE
Add Waymarked Trails layers

### ISSUE THREAD

**Issue by jbelien** [WelcometoMyGarden/welcometomygarden#4]
Request from @Driesvanransbeeck : display Hiking/Cycling Waymarked Trails layers as overlay on the map

1. Use Mapbox GL Raster Source
    - Documentation: https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#raster
    - Example: https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/
1. URL:
    - Hiking: `https://tile.waymarkedtrails.org/hiking/{z}/{x}/{y}.png`
    - Cycling: `https://tile.waymarkedtrails.org/cycling/{z}/{x}/{y}.png`
1. Add control to show/hide overlay layers

---

Tile usage:

> Règles d’utilisation
>
> Vous pouvez utiliser la superposition d’itinéraires sur d’autres sites tant que les fréquences d’accès restent modérées. Veuillez mettre en cache les tuiles aussi souvent que possible et utiliser un référent correct. Le téléchargement massif de tuiles est fortement découragé.
> -- https://hiking.waymarkedtrails.org/help/legal

Maybe worth contacting them to ask for permission!

**Comment by Driesvanransbeeck** [comment]
I'm going to ask permission to Waymarked Trails today. Thank you Jonathan!

**Comment by Driesvanransbeeck** [comment]
As suggested by @jbelien, it would be great to add the hillshades tiles too: https://openmaptiles.com/hillshades/.

**Comment by jbelien** [comment]
@MichielLeyman Beautifully executed 👌

**Comment by Driesvanransbeeck** [comment]
Indeed, brilliant work! Thank you for those layers Michiel!
