### ISSUE TITLE
Content overflows on host cards if they have the maximum amount of content

### ISSUE THREAD

**Issue by borisrorsvort** [WelcometoMyGarden/welcometomygarden#40]
browser: Safari Version 13.1.1 (15609.2.9.1.2) mais aussi latest chrome

url to reproduce: https://welcometomygarden.org/explore/garden/Q7iAS9oTMwR9lsd6BNeC

<img width="609" alt="CleanShot 2020-06-29 at 17 18 12@2x" src="https://user-images.githubusercontent.com/39081/86023930-a357f780-ba2c-11ea-83b8-7285db021d31.png">

**Comment by nicklace** [comment]
Adding (for desktop)
```
max-height: 20vh;
overflow-y: scroll;
display: block;
```
To **.main p.text**  element shoulf fix this by adding a scrollbar for long content.
