### ISSUE TITLE
Add hillshade layer

### ISSUE THREAD

**Issue by jbelien** [WelcometoMyGarden/welcometomygarden#5]
As suggested by @jbelien, it would be great to add the hillshades tiles too: https://openmaptiles.com/hillshades/.

_Originally posted by @Driesvanransbeeck in https://github.com/WelcometoMyGarden/welcometomygarden/issues/4#issuecomment-634488505_

**Comment by jbelien** [comment]
Need to find a provider for hillshade layer !

**Comment by auloin** [comment]
We're now using Mapbox Streets style https://www.mapbox.com/maps/streets (#138). Decision was made after trying Mapbox 
Outdoors which turned out to be quite slow.
