### ISSUE TITLE
Availability calendar for a garden

### ISSUE THREAD

**Issue by brentguf** [WelcometoMyGarden/welcometomygarden#52]

**Comment by MichielLeyman** [comment]
I suppose this would be part of a broader "booking system". I'm wondering if listing and unlisting a garden is the farthest extent we want to go to.

@Driesvanransbeeck @Manonbd thoughts?

**Comment by Manonbd** [comment]
I think it will be too much assimilated to airbnb or paid services. Unlisting the garden is sufficient in my opinion!

**Comment by MichielLeyman** [comment]
Closing this until unlisting proves itself to be insufficient. Thanks for the input :)
