### ISSUE TITLE
Position of language picker

### ISSUE THREAD

**Issue by brentguf** [WelcometoMyGarden/welcometomygarden#53]
To be discussed. Maybe at the bottom is not very visible?

**Comment by MichielLeyman** [comment]
Which alternate position would you choose? I don't think the main nav bar is the right place for it

**Comment by MichielLeyman** [comment]
I'm also not sure if the language picker needs better visibility, since the default language is derived from the user's browser settings

**Comment by MichielLeyman** [comment]
Doesn't seem like a problem that needs to be fixed for now - we can revisit this when we get support emails that show this is necessary.
