### ISSUE TITLE
Adjust center of the map based on the user

### ISSUE THREAD

**Issue by MichielLeyman** [WelcometoMyGarden/welcometomygarden#55]
Right now, the center of the map on page load is always a hardcoded latitude and longitude, the center of Belgium.

I propose we do the following:

- [ ] If a user has a garden, set its location as the map's center
- [ ] We can make a geolocation request using user IP (https://geolocation-db.com/json/) to get someone's approximate location
- [ ] If the request fails or is blocked and the user is logged in, we can default to the country they provide on registration
- [x] We can ask for the user's location, but I'd find that annoying. I'd default to Belgium if all else fails. 

This makes it so that we can increase the zoom level a little, since right now you see a lot you probably don't want to when you first load the page.

This is also the only missing (technical) thing that is preventing widespread use outside of Belgium.

**Comment by wardbeyens** [comment]
We ask for the user's location if they give us permission, we center the map otherwise it defaults to Belgium.
