### ISSUE TITLE
Add 'search' tool to type location

### ISSUE THREAD

**Issue by iLienstAr** [WelcometoMyGarden/welcometomygarden#61]
Suggestion of user:

Add search tool so you can also search on names of places, next to the map-zoom-search.

**Comment by wardbeyens** [comment]
This is also included in this issue I think #51

**Comment by wardbeyens** [comment]
video: https://cloud.wabyte.com/index.php/s/JsmdbBdb5xxEJtq

The user types in the input field, if the user stops typing for 250 milliseconds then there are (normally) 5 results, i.e. 5 place names displayed below the input field.
These results appear and disappear with a fade-in (50ms) and fade-out (200ms).

If the user clicks on 1 of the results (i.e. 1 location) the map will zoom in to this location. The input field will be cleared and the results will disappear.

Currently, the search is limited to cities and villages and the results are displayed in the language of the user.

If the user searches for a location and none is found a message "no places found" will be displayed for 3 seconds.

If the results are still on the screen, but the user clicks not on one of the locations, but on the map. Then the input field will be emptied as the results. (When the user drags the map, the locations WILL be displayed)

Future possibilities:
- accessibility, 'tab' 'shift tab' 'arrow up' 'arrow down' 'enter' => go over the places list, enter for selecting the place.
- dynamic zoom, search for Bruxelles zoom=10, search for small village zoom= 13 https://wiki.openstreetmap.org/wiki/Zoom_levels

known issue: 
- phone, while typing the search results are displayed over the trails box and not all the results are visible. (don't know how to fix)
link image not typing: https://cloud.wabyte.com/index.php/s/c3PKi7bPSPfwTsR
link image typing: https://cloud.wabyte.com/index.php/s/mK5K78L5MYyH84d

![](https://cloud.wabyte.com/index.php/s/mK5K78L5MYyH84d/preview)

**Comment by wardbeyens** [comment]
possible fix:
![](https://cloud.wabyte.com/index.php/s/xCaQAWBqAwLFYRs)

**Comment by wardbeyens** [comment]
After talking to the designer, we will display "(village,) town, province" instead of the original "(village,) town, province, country"
