### ISSUE TITLE
Develop 'our supporters' section on landing page

### ISSUE THREAD

**Issue by Driesvanransbeeck** [WelcometoMyGarden/welcometomygarden#8]
Above the footer, we'd like to have an 'our supporters' section containing 2 equal blocks.

- On the left hand side: Donations from individuals, with as text "Welcome to My Garden is a not-for-profit initiative that can only stay alive with the support of the community. You can help maintain and improve this initiative with a donation" & a link to our Open Collective page: https://opencollective.com/welcometomygarden.

- On the right hand side: Overview of our supporting organisations with their logos. It's not confirmed yet which organisations will be mentioned, but it would be great to already create a placeholder.

**Comment by hektormisplon** [comment]
A nice to have would be to use the ["Open Collective" api](https://docs.opencollective.com/help/contributing/development/api/collectives) to display donations dynamically. (e.g. latest/biggest financial contributor)

It also allows us to display some other stuff:

e.g. [This endpoint](https://opencollective.com/welcometomygarden/members/all.json) allows us to list all contributors

**Comment by Driesvanransbeeck** [comment]
Can we add the partner section - next to the support us section - with the following 2 logos to the homepage?

- Logo Open Knowledge Belgium referring to openknowledge.be
- [Logo](https://n-cloud.vgc.be/s/Na44NdNPHGidRE8?path=%2F) VGC Staycation Brussels referring to staycation.brussels

**Comment by MichielLeyman** [comment]
Partner section :heavy_check_mark: (thanks Brent!)

@Driesvanransbeeck do we still want the Open Collective backers listed in the donation section?
