### ISSUE TITLE
Relocate service-worker

### ISSUE THREAD

**Issue by wardbeyens** [WelcometoMyGarden/welcometomygarden#86]
It is more convenient if the service-worker is at the root level.
Also this:
`
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('http://localhost:5000/') with script ('http://localhost:5000/service-worker.js'): The script has an unsupported MIME type ('text/html').`

**Comment by MichielLeyman** [comment]
This actually fixed itself after redoing the build process in  #71. https://github.com/WelcometoMyGarden/welcometomygarden/blob/master/src/main.js, this works on staging and will be live on the next deploy.
