### ISSUE TITLE
Add legal section to website

### ISSUE THREAD

**Issue by Driesvanransbeeck** [WelcometoMyGarden/welcometomygarden#9]
We're working on our privacy policy, cookies policy & term of use (work in progress). 

Inspired by the way it's done on https://www.citizenlab.co/legals, we'd like to add a similar page to our website + add it to the footer on our landing page. 

The text of the policies will be ready soon. Meanwhile, we can already create this page + add it to our footer.

**Comment by hektormisplon** [comment]
- [x] Privacy policy
- [x] Cookies policy
- [x] Terms of use
- [ ] Copyright  
#17

**Comment by MichielLeyman** [comment]
Closed in #17 
No copy, designs or history to be found for a "copyright" page.

Thank you Hektor!
