### ISSUE TITLE
Add a reconfirmation button for the travellers

### ISSUE THREAD

**Issue by Manonbd** [WelcometoMyGarden/welcometomygarden#95]
Request from hosts: add a renconfirmation button for travellers as travellers tend to confirm but not show up.

**Comment by MichielLeyman** [comment]
What would a button such as this do? Send a reminder to the traveller who messaged the host?

**Comment by MichielLeyman** [comment]
Closing until we decide on a future possible booking system or something that would allow us to implement this. Feel free to clarify and I can reopen the issue :)
